[pytest]
pythonpath = .
testpaths = tests
base_url = https://www.saucedemo.com
addopts = --browser chromium --screenshot only-on-failure --output reports/artifacts --html=reports/report.html --self-contained-html
markers =
    smoke: quick basic checks
    regression: full test run